name: docker-ci

on:
  push:
    tags:        
      - "v*"

jobs:
  docker-ci:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
             quay.io/${{ github.repository }}
             docker.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        with:
          install: true
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}+github
          password: ${{ secrets.BOT_QUAY_IO }}

      - name: Login to docker.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.USER_DOCKER_IO }}
          password: ${{ secrets.BOT_DOCKER_IO }}

      - name: Build and push
        id: build-release
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            KUBECTL_VERSION=${{ steps.meta.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.build-release.outputs.digest }}
