name: Weekly check

on:
  schedule:
    # Every Monday at 9AM
    - cron: '0 9 * * 1'
jobs:
  check-kubectl-new-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get latest tag from the repository
        id: repository
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Get latest kubectl release
        id: remote
        run: echo "version=$(curl https://cdn.dl.k8s.io/release/stable.txt)" >> $GITHUB_OUTPUT

      - name: Debug outputs
        run: |
          echo "Repository version: ${{ steps.repository.outputs.version }}"
          echo "Remote version: ${{ steps.remote.outputs.version }}"

      - name: Create new tag
        if: ${{ steps.repository.outputs.version != steps.remote.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email 'github-actions@users.noreply.github.com'
          git tag -a "${{ steps.remote.outputs.version }}" -m "New release"
          git push origin "${{ steps.remote.outputs.version }}"
